name: argos-ui
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: argos-ui       # <- adjust if your UI folder name differs
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            argos-ui/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('argos-ui/package-lock.json', 'argos-ui/yarn.lock', 'argos-ui/pnpm-lock.yaml') }}

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci --no-audit --no-fund;
          elif [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i --frozen-lockfile;
          elif [ -f yarn.lock ]; then npm i -g yarn && yarn install --frozen-lockfile;
          else npm i; fi

      - name: Lint/Test/Build (non-fatal if script missing)
        run: |
          npm run -s lint --if-present
          npm run -s test --if-present
          npm run -s build --if-present

      - name: Upload build (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: argos-ui-build
          path: |
            dist
            build
          if-no-files-found: ignore
